### ISSUE TITLE
Error deploying to Heroku

### ISSUE THREAD

**Issue by brian-hay** [endel/babylonjs-multiplayer-boilerplate#1]
Tried Heroku deployment but got the following error:

>>>
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  6.9.1
       engines.npm (package.json):   unspecified (use default)
       
       Downloading and installing node 6.9.1...
       Using default npm version: 3.10.8
-----> Restoring cache
       Skipping cache restore (new runtime signature)
-----> Building dependencies
       Installing node modules (package.json)
       
       > babylonjs-colyseus@1.0.0 install /tmp/build_5f94ecac3f7ac0e13ce63cf17d1ecf3d/endel-babylonjs-multiplayer-boilerplate-20c1350
       > npm run compile-server && npm run compile-client
       
       
       > babylonjs-colyseus@1.0.0 compile-server /tmp/build_5f94ecac3f7ac0e13ce63cf17d1ecf3d/endel-babylonjs-multiplayer-boilerplate-20c1350
       > npm install --prefix server && tsc -p server
       
       babylonjs-colyseus-server@1.0.0 /tmp/build_5f94ecac3f7ac0e13ce63cf17d1ecf3d/endel-babylonjs-multiplayer-boilerplate-20c1350/server
       ├── @types/cors@0.0.33
       ├─┬ @types/express@4.0.34
       │ ├── @types/express-serve-static-core@4.0.39
       │ └─┬ @types/serve-static@1.7.31
       │   └── @types/mime@0.0.29
       ├── @types/node@6.0.51
       ├── @types/shortid@0.0.28
       ├─┬ colyseus@0.4.4
       │ ├── @types/fossil-delta@0.2.2
       │ ├── @types/mocha@2.2.33
       │ ├── @types/msgpack-lite@0.1.1
       │ ├── @types/ws@0.0.35
       │ ├─┬ clock-timer.js@1.1.4
       │ │ └── clock.js@1.1.5
       │ ├── fossil-delta@0.2.5
       │ ├─┬ msgpack-lite@0.1.26
       │ │ ├── event-lite@0.1.1
       │ │ ├── ieee754@1.1.8
       │ │ ├── int64-buffer@0.1.9
       │ │ └── isarray@1.0.0
       │ ├─┬ timeframe@0.3.5
       │ │ └── harmony-proxy@1.0.1
       │ └─┬ ws@1.1.1
       │   ├── options@0.0.6
       │   └── ultron@1.0.2
       ├─┬ cors@2.8.1
       │ └── vary@1.1.0
       ├─┬ express@4.14.0
       │ ├─┬ accepts@1.3.3
       │ │ ├─┬ mime-types@2.1.13
       │ │ │ └── mime-db@1.25.0
       │ │ └── negotiator@0.6.1
       │ ├── array-flatten@1.1.1
       │ ├── content-disposition@0.5.1
       │ ├── content-type@1.0.2
       │ ├── cookie@0.3.1
       │ ├── cookie-signature@1.0.6
       │ ├─┬ debug@2.2.0
       │ │ └── ms@0.7.1
       │ ├── depd@1.1.0
       │ ├── encodeurl@1.0.1
       │ ├── escape-html@1.0.3
       │ ├── etag@1.7.0
       │ ├─┬ finalhandler@0.5.0
       │ │ ├── statuses@1.3.1
       │ │ └── unpipe@1.0.0
       │ ├── fresh@0.3.0
       │ ├── merge-descriptors@1.0.1
       │ ├── methods@1.1.2
       │ ├─┬ on-finished@2.3.0
       │ │ └── ee-first@1.1.1
       │ ├── parseurl@1.3.1
       │ ├── path-to-regexp@0.1.7
       │ ├─┬ proxy-addr@1.1.2
       │ │ ├── forwarded@0.1.0
       │ │ └── ipaddr.js@1.1.1
       │ ├── qs@6.2.0
       │ ├── range-parser@1.2.0
       │ ├─┬ send@0.14.1
       │ │ ├── destroy@1.0.4
       │ │ ├─┬ http-errors@1.5.1
       │ │ │ ├── inherits@2.0.3
       │ │ │ └── setprototypeof@1.0.2
       │ │ └── mime@1.3.4
       │ ├── serve-static@1.11.1
       │ ├─┬ type-is@1.6.14
       │ │ └── media-typer@0.3.0
       │ └── utils-merge@1.0.0
       └── shortid@2.2.6
       
       sh: 1: tsc: not found
       
       npm ERR! Linux 3.13.0-105-generic
       npm ERR! argv "/tmp/build_5f94ecac3f7ac0e13ce63cf17d1ecf3d/endel-babylonjs-multiplayer-boilerplate-20c1350/.heroku/node/bin/node" "/tmp/build_5f94ecac3f7ac0e13ce63cf17d1ecf3d/endel-babylonjs-multiplayer-boilerplate-20c1350/.heroku/node/bin/npm" "run" "compile-server"
       npm ERR! node v6.9.1
       npm ERR! npm  v3.10.8
       npm ERR! file sh
       npm ERR! code ELIFECYCLE
       npm ERR! errno ENOENT
       npm ERR! syscall spawn
       npm ERR! babylonjs-colyseus@1.0.0 compile-server: `npm install --prefix server && tsc -p server`
       npm ERR! spawn ENOENT
       npm ERR!
       npm ERR! Failed at the babylonjs-colyseus@1.0.0 compile-server script 'npm install --prefix server && tsc -p server'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the babylonjs-colyseus package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     npm install --prefix server && tsc -p server
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs babylonjs-colyseus
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls babylonjs-colyseus
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_5f94ecac3f7ac0e13ce63cf17d1ecf3d/endel-babylonjs-multiplayer-boilerplate-20c1350/npm-debug.log
       
       npm ERR! Linux 3.13.0-105-generic
       npm ERR! argv "/tmp/build_5f94ecac3f7ac0e13ce63cf17d1ecf3d/endel-babylonjs-multiplayer-boilerplate-20c1350/.heroku/node/bin/node" "/tmp/build_5f94ecac3f7ac0e13ce63cf17d1ecf3d/endel-babylonjs-multiplayer-boilerplate-20c1350/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_5f94ecac3f7ac0e13ce63cf17d1ecf3d/endel-babylonjs-multiplayer-boilerplate-20c1350/.npmrc"
       npm ERR! node v6.9.1
       npm ERR! npm  v3.10.8
       npm ERR! code ELIFECYCLE
       npm ERR! babylonjs-colyseus@1.0.0 install: `npm run compile-server && npm run compile-client`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the babylonjs-colyseus@1.0.0 install script 'npm run compile-server && npm run compile-client'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the babylonjs-colyseus package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     npm run compile-server && npm run compile-client
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs babylonjs-colyseus
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls babylonjs-colyseus
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_5f94ecac3f7ac0e13ce63cf17d1ecf3d/endel-babylonjs-multiplayer-boilerplate-20c1350/npm-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
>>>

**Comment by endel** [comment]
Hi @brian-hay, 

If you're pushing to heroku without using the "deploy" button, you'll need to set the `NPM_CONFIG_PRODUCTION` to `false`.

```
heroku config:set NPM_CONFIG_PRODUCTION=false
```

Then heroku will install the dev dependencies and build the project in their side normally.

Please let me know if it works for you.
Cheers!

**Comment by brian-hay** [comment]
Using "deploy" button and leaving `NPM_CONFIG_PRODUCTION` as default `false` worked. Trying "deploy" button again but changing to `true` failed. Sorry I'm new to this.

**Comment by endel** [comment]
@brian-hay don't worry. it should be set to `false`.

**Comment by brian-hay** [comment]
Thanks @endel
