### ISSUE TITLE
Time out when deploying 

### ISSUE THREAD

**Issue by dragonmaths** [endel/babylonjs-multiplayer-boilerplate#2]
Maybe because I did some name changes as at https://github.com/dragonmaths/nine-clone-morris but I keep getting a timeout error when pushing

`       [at-loader] Using typescript@2.2.0-dev.20161211 from typescript and "tsconfig.json" from /tmp/build_37b2f289e9503b7a3455af4760078e9f/client/tsconfig.json

       

       

       [at-loader] Checking started in a separate process...

       

       [at-loader] Ok, 0.69 sec.

       Hash: 75ebb67a17d978ba98a4

       Version: webpack 2.1.0-beta.27

       Time: 5931ms

       Asset       Size  Chunks             Chunk Names

       bundle.js    1.55 MB       0  [emitted]  main

       styles.css  135 bytes       0  [emitted]  main

       bundle.js.map    1.62 MB       0  [emitted]  main

       styles.css.map   83 bytes       0  [emitted]  main

       index.html  265 bytes          [emitted]

       + 79 hidden modules

       Child html-webpack-plugin for "index.html":

       + 4 hidden modules

       Child extract-text-webpack-plugin:

       + 2 hidden modules

 !     Timed out compiling app (60 minutes)

 !     See https://devcenter.heroku.com/articles/slug-compiler#time-limit`

after Child extract-text-webpack-plugin:

**Comment by endel** [comment]
Hi @dragonmaths,

Indeed, I could reproduce the problem. It seems `awesome-typescript-loader` is being updated, and forcing the version to `3.0.0-beta.9` worked. Also, yesterday I updated one of `colyseus.js` dependencies, and this caused some warnings. I just fixed that.

Can you update the `awesome-typescript-loader` in your side as well? https://github.com/endel/babylonjs-multiplayer-boilerplate/commit/8ea4bdb6397965ef499f3ae34cdab86d599aba47

Please let me know if it works.
Cheers!

**Comment by dragonmaths** [comment]
Thank you for your prompt reply, sorry I was so slow getting back to it. It now works well on the web. Brilliant thank you.
